# Generated by Django 5.1.4 on 2024-12-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colegioapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calificacion",
            name="especificacion",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="calificacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("NOTA 1", "Nota 1"),
                    ("NOTA 2", "Nota 2"),
                    ("NOTA 3", "Nota 3"),
                    ("NOTA 4", "Nota 4"),
                    ("NOTA 5", "Nota 5"),
                ],
                max_length=20,
            ),
        ),
    ]
