# Generated by Django 5.1.4 on 2025-01-28 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colegioapp", "0002_calificacion_especificacion_alter_calificacion_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField()),
                ("observacion", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="pagomensualidad",
            name="año_no_futuro",
        ),
        migrations.AddConstraint(
            model_name="pagomensualidad",
            constraint=models.CheckConstraint(
                condition=models.Q(("año__lte", 2025)), name="año_no_futuro"
            ),
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="asignatura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluaciones",
                to="colegioapp.asignatura",
            ),
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="profesor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluaciones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
