# Generated by Django 5.1.4 on 2025-01-28 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colegioapp", "0003_evaluacion_remove_pagomensualidad_año_no_futuro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calificacion",
            name="especificacion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="calificacion",
            name="nota",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(7.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("PROFESOR", "Profesor"),
                    ("ALUMNO", "Alumno"),
                    ("APODERADO", "Apoderado"),
                    ("SECRETARIA", "Secretaria"),
                    ("DIRECTOR", "Director"),
                ],
                max_length=20,
            ),
        ),
    ]
