# Generated by Django 5.1.4 on 2025-02-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colegioapp", "0005_anotacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroasistencia",
            name="fecha_hora",
            field=models.DateTimeField(),
        ),
    ]
