# Generated by Django 5.1.4 on 2025-02-20 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colegioapp", "0006_alter_registroasistencia_fecha_hora"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bitacora",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateField()),
                ("observacion", models.TextField()),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bitacoras",
                        to="colegioapp.asignatura",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        limit_choices_to={"rol": "PROFESOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
