# Generated by Django 5.1.4 on 2025-02-20 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colegioapp", "0007_bitacora"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bitacora",
            name="asignatura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="colegioapp.asignatura"
            ),
        ),
        migrations.AlterField(
            model_name="bitacora",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
